# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    calculate_feature_density as calculate_feature_density,
)
from ecoscope.platform.tasks.analysis import create_meshgrid as create_meshgrid
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import (
    set_list_of_string_vars as set_list_of_string_vars,
)
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import get_events as get_events
from ecoscope.platform.tasks.io import (
    get_patrol_observations as get_patrol_observations,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import create_polygon_layer as create_polygon_layer
from ecoscope.platform.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    all_keyed_iterables_are_skips as all_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    drop_nan_values_by_column as drop_nan_values_by_column,
)
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)
from ecoscope.platform.tasks.transformation import filter_df as filter_df
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_ext_custom.tasks.transformation import (
    decompose_datetime as decompose_datetime,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    exclude_row_values as exclude_row_values,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations)
        .validate()
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=False,
            sub_page_size=None,
            **(params.get("patrol_obs") or {}),
        )
        .call()
    )

    events_data = (
        task(get_events)
        .validate()
        .set_task_instance_id("events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "geometry",
            ],
            raise_on_empty=False,
            include_null_geometry=True,
            include_display_values=True,
            **(params.get("events_data") or {}),
        )
        .call()
    )

    set_summary_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_summary_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Patrol Effort Summary", **(params.get("set_summary_title") or {}))
        .call()
    )

    set_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Patrols & Events Map", **(params.get("set_map_title") or {}))
        .call()
    )

    set_coverage_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_coverage_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Patrol Coverage Map", **(params.get("set_coverage_map_title") or {})
        )
        .call()
    )

    set_event_density_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_event_density_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Event Density Map", **(params.get("set_event_density_title") or {})
        )
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    exclude_rangers = (
        task(set_list_of_string_vars)
        .validate()
        .set_task_instance_id("exclude_rangers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("exclude_rangers") or {}))
        .call()
    )

    convert_patrols_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params.get("convert_patrols_tz") or {}),
        )
        .call()
    )

    patrol_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("patrol_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_patrols_tz,
            relocs_columns=[
                "patrol_id",
                "patrol_start_time",
                "patrol_end_time",
                "patrol_type__value",
                "patrol_type__display",
                "patrol_serial_number",
                "patrol_status",
                "patrol_subject",
                "groupby_col",
                "fixtime",
                "junk_status",
                "extra__source",
                "geometry",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("patrol_reloc") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(relocations=patrol_reloc, **(params.get("patrol_traj") or {}))
        .call()
    )

    traj_rename_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_rename_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__patrol_subject": "patrol_subject",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_type__value": "patrol_type__value",
                "extra__patrol_status": "patrol_status",
            },
            raise_if_not_found=False,
            **(params.get("traj_rename_cols") or {}),
        )
        .call()
    )

    traj_exclude_rangers = (
        task(exclude_row_values)
        .validate()
        .set_task_instance_id("traj_exclude_rangers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_cols,
            column="patrol_subject",
            values=exclude_rangers,
            **(params.get("traj_exclude_rangers") or {}),
        )
        .call()
    )

    traj_with_date = (
        task(decompose_datetime)
        .validate()
        .set_task_instance_id("traj_with_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_exclude_rangers,
            datetime_column="segment_start",
            components=["date"],
            remove_source=False,
            **(params.get("traj_with_date") or {}),
        )
        .call()
    )

    convert_events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_data,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_tz") or {}),
        )
        .call()
    )

    extract_reported_by = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_reported_by")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_tz,
            column_name="reported_by",
            field_name_options=["name"],
            output_type="str",
            output_column_name="reported_by_name",
            **(params.get("extract_reported_by") or {}),
        )
        .call()
    )

    events_with_reporter = (
        task(filter_df)
        .validate()
        .set_task_instance_id("events_with_reporter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_reported_by,
            column_name="reported_by_name",
            op="ne",
            value="None",
            reset_index=True,
            **(params.get("events_with_reporter") or {}),
        )
        .call()
    )

    events_exclude_rangers = (
        task(exclude_row_values)
        .validate()
        .set_task_instance_id("events_exclude_rangers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_with_reporter,
            column="reported_by_name",
            values=exclude_rangers,
            **(params.get("events_exclude_rangers") or {}),
        )
        .call()
    )

    events_filter = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("events_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_exclude_rangers,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            **(params.get("events_filter") or {}),
        )
        .call()
    )

    events_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("events_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_filter,
            input_column_name="event_type",
            colormap="tab20b",
            output_column_name="event_type_colormap",
            **(params.get("events_colormap") or {}),
        )
        .call()
    )

    split_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_with_date,
            groupers=groupers,
            **(params.get("split_traj_groups") or {}),
        )
        .call()
    )

    split_event_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_event_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_colormap,
            groupers=groupers,
            **(params.get("split_event_groups") or {}),
        )
        .call()
    )

    summary_table_df = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("summary_table_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(reset_index=True, **(params.get("summary_table_df") or {}))
        .mapvalues(argnames=["df"], argvalues=split_traj_groups)
    )

    summary_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("summary_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"patrol_subject": "Ranger"},
            raise_if_not_found=False,
            **(params.get("summary_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=summary_table_df)
    )

    summary_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=None,
            widget_id=set_summary_title,
            table_config={
                "enable_sorting": True,
                "enable_filtering": False,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("summary_table") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=summary_rename)
    )

    summary_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("summary_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="summary_table",
            **(params.get("summary_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=summary_table)
    )

    summary_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("summary_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_summary_title, **(params.get("summary_widget") or {}))
        .map(argnames=["view", "data"], argvalues=summary_html)
    )

    summary_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("summary_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=summary_widget, **(params.get("summary_widget_merged") or {}))
        .call()
    )

    traj_display_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_display_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "patrol_subject": "Patrol Subject",
                "segment_start": "Start",
                "speed_kmhr": "Speed (kph)",
            },
            raise_if_not_found=False,
            **(params.get("traj_display_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_traj_groups)
    )

    traj_polyline_layer = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("traj_polyline_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_color": [80, 80, 80],
                "color_column": None,
                "get_width": 3,
                "width_units": "pixels",
                "cap_rounded": True,
                "opacity": 1,
            },
            legend=None,
            tooltip_columns=["Patrol Subject", "Start", "Speed (kph)"],
            **(params.get("traj_polyline_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=traj_display_rename)
    )

    events_display_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("events_display_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "serial_number": "Event Serial",
                "time": "Event Time",
                "event_type_display": "Event Type",
                "reported_by_name": "Reported By",
            },
            raise_if_not_found=False,
            **(params.get("events_display_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_event_groups)
    )

    event_point_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("event_point_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"fill_color_column": "event_type_colormap", "get_radius": 5},
            legend={
                "label_column": "Event Type",
                "color_column": "event_type_colormap",
            },
            tooltip_columns=["Event Serial", "Event Time", "Event Type", "Reported By"],
            **(params.get("event_point_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=events_display_rename)
    )

    map_layers_zip = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("map_layers_zip")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                all_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[traj_polyline_layer, event_point_layer],
            **(params.get("map_layers_zip") or {}),
        )
        .call()
    )

    map_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("map_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Event Type",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_map_title,
            **(params.get("map_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=map_layers_zip)
    )

    map_ecomap_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("map_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ranger_map",
            **(params.get("map_ecomap_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=map_ecomap)
    )

    map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_map_title, **(params.get("map_widget") or {}))
        .map(argnames=["view", "data"], argvalues=map_ecomap_html)
    )

    map_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("map_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=map_widget, **(params.get("map_widget_merged") or {}))
        .call()
    )

    coverage_meshgrid = (
        task(create_meshgrid)
        .validate()
        .set_task_instance_id("coverage_meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=traj_with_date,
            intersecting_only=False,
            **(params.get("coverage_meshgrid") or {}),
        )
        .call()
    )

    grouped_coverage_density = (
        task(calculate_feature_density)
        .validate()
        .set_task_instance_id("grouped_coverage_density")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            meshgrid=coverage_meshgrid,
            geometry_type="line",
            **(params.get("grouped_coverage_density") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_traj_groups)
    )

    coverage_sorted = (
        task(sort_values)
        .validate()
        .set_task_instance_id("coverage_sorted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="density",
            ascending=True,
            na_position="last",
            **(params.get("coverage_sorted") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=grouped_coverage_density)
    )

    coverage_drop_nan = (
        task(drop_nan_values_by_column)
        .validate()
        .set_task_instance_id("coverage_drop_nan")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="density", **(params.get("coverage_drop_nan") or {}))
        .mapvalues(argnames=["df"], argvalues=coverage_sorted)
    )

    coverage_classify = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("coverage_classify")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density",
            output_column_name="density_bins",
            classification_options={"scheme": "equal_interval", "k": 10},
            label_options={"label_ranges": True, "label_decimals": 0},
            **(params.get("coverage_classify") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=coverage_drop_nan)
    )

    coverage_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("coverage_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap="viridis",
            output_column_name="density_colormap",
            **(params.get("coverage_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=coverage_classify)
    )

    coverage_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("coverage_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"density": "Patrol Effort"},
            raise_if_not_found=True,
            **(params.get("coverage_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=coverage_colormap)
    )

    coverage_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("coverage_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "density_colormap",
                "get_line_width": 0,
                "opacity": 0.4,
            },
            legend={"label_column": "density_bins", "color_column": "density_colormap"},
            tooltip_columns=["Patrol Effort"],
            **(params.get("coverage_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=coverage_rename)
    )

    coverage_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("coverage_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Patrol Effort",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_coverage_map_title,
            **(params.get("coverage_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=coverage_layer)
    )

    coverage_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("coverage_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="coverage_map",
            **(params.get("coverage_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=coverage_ecomap)
    )

    coverage_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("coverage_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_coverage_map_title, **(params.get("coverage_widget") or {}))
        .map(argnames=["view", "data"], argvalues=coverage_html)
    )

    coverage_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("coverage_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=coverage_widget, **(params.get("coverage_widget_merged") or {})
        )
        .call()
    )

    event_meshgrid = (
        task(create_meshgrid)
        .validate()
        .set_task_instance_id("event_meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=events_colormap,
            intersecting_only=False,
            **(params.get("event_meshgrid") or {}),
        )
        .call()
    )

    grouped_event_density = (
        task(calculate_feature_density)
        .validate()
        .set_task_instance_id("grouped_event_density")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            meshgrid=event_meshgrid,
            geometry_type="point",
            sum_column=None,
            **(params.get("grouped_event_density") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_event_groups)
    )

    ed_sorted = (
        task(sort_values)
        .validate()
        .set_task_instance_id("ed_sorted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="density",
            ascending=True,
            na_position="last",
            **(params.get("ed_sorted") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=grouped_event_density)
    )

    ed_drop_nan = (
        task(drop_nan_values_by_column)
        .validate()
        .set_task_instance_id("ed_drop_nan")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="density", **(params.get("ed_drop_nan") or {}))
        .mapvalues(argnames=["df"], argvalues=ed_sorted)
    )

    ed_classify = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("ed_classify")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density",
            output_column_name="density_bins",
            classification_options={"scheme": "equal_interval", "k": 10},
            label_options={"label_ranges": True, "label_decimals": 0},
            **(params.get("ed_classify") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ed_drop_nan)
    )

    ed_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("ed_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap="RdYlGn_r",
            output_column_name="density_colormap",
            **(params.get("ed_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ed_classify)
    )

    ed_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("ed_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"density": "Event Count"},
            raise_if_not_found=True,
            **(params.get("ed_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ed_colormap)
    )

    ed_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("ed_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "density_colormap",
                "get_line_width": 0,
                "opacity": 0.4,
            },
            legend={"label_column": "density_bins", "color_column": "density_colormap"},
            tooltip_columns=["Event Count"],
            **(params.get("ed_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=ed_rename)
    )

    ed_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("ed_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Number of Events",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_event_density_title,
            **(params.get("ed_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=ed_layer)
    )

    ed_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("ed_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="event_density_map",
            **(params.get("ed_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ed_ecomap)
    )

    ed_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("ed_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_event_density_title, **(params.get("ed_widget") or {}))
        .map(argnames=["view", "data"], argvalues=ed_html)
    )

    ed_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("ed_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=ed_widget, **(params.get("ed_widget_merged") or {}))
        .call()
    )

    ranger_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("ranger_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                summary_widget_merged,
                map_widget_merged,
                coverage_widget_merged,
                ed_widget_merged,
            ],
            groupers=groupers,
            time_range=time_range,
            **(params.get("ranger_dashboard") or {}),
        )
        .call()
    )

    return ranger_dashboard
