# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    calculate_feature_density as calculate_feature_density,
)
from ecoscope.platform.tasks.analysis import (
    get_density_legend_title as get_density_legend_title,
)
from ecoscope.platform.tasks.analysis import (
    normalize_density_units as normalize_density_units,
)
from ecoscope.platform.tasks.analysis import (
    set_density_weighting as set_density_weighting,
)
from ecoscope.platform.tasks.analysis import (
    set_patrol_summary_metrics as set_patrol_summary_metrics,
)
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import (
    call_meshgrid_from_combined_params as call_meshgrid_from_combined_params,
)
from ecoscope.platform.tasks.config import (
    get_opacity_from_combined_params as get_opacity_from_combined_params,
)
from ecoscope.platform.tasks.config import (
    set_density_grid_options as set_density_grid_options,
)
from ecoscope.platform.tasks.config import (
    set_list_of_string_vars as set_list_of_string_vars,
)
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import (
    get_event_type_display_names_from_events as get_event_type_display_names_from_events,
)
from ecoscope.platform.tasks.io import (
    get_patrol_observations_from_patrols_df_and_combined_params as get_patrol_observations_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.io import (
    get_patrols_from_combined_params as get_patrols_from_combined_params,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope.platform.tasks.io import (
    unpack_events_from_patrols_df_and_combined_params as unpack_events_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_point_layer as create_point_layer
from ecoscope.platform.tasks.results import create_polygon_layer as create_polygon_layer
from ecoscope.platform.tasks.results import (
    create_polyline_layer as create_polyline_layer,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import (
    all_keyed_iterables_are_skips as all_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    drop_nan_values_by_column as drop_nan_values_by_column,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import sort_values as sort_values
from ecoscope_workflows_ext_custom.tasks.config import (
    get_bounding_box as get_bounding_box,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_filter_point_coords as get_filter_point_coords,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_segment_filter as get_segment_filter,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    set_traj_filters as set_traj_filters,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    decompose_datetime as decompose_datetime,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    er_patrol_and_events_params = (
        task(set_patrols_and_patrol_events_params)
        .validate()
        .set_task_instance_id("er_patrol_and_events_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            include_patrol_details=True,
            raise_on_empty=False,
            truncate_to_time_range=True,
            include_null_geometry=True,
            sub_page_size=100,
            **(params.get("er_patrol_and_events_params") or {}),
        )
        .call()
    )

    prefetch_patrols = (
        task(get_patrols_from_combined_params)
        .validate()
        .set_task_instance_id("prefetch_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=er_patrol_and_events_params,
            **(params.get("prefetch_patrols") or {}),
        )
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_and_events_params,
            **(params.get("patrol_obs") or {}),
        )
        .call()
    )

    patrol_events = (
        task(unpack_events_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_and_events_params,
            **(params.get("patrol_events") or {}),
        )
        .call()
    )

    event_type_display_names = (
        task(get_event_type_display_names_from_events)
        .validate()
        .set_task_instance_id("event_type_display_names")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            events_gdf=patrol_events,
            append_category_names="duplicates",
            **(params.get("event_type_display_names") or {}),
        )
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    set_summary_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_summary_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Patrol Effort Summary", **(params.get("set_summary_title") or {}))
        .call()
    )

    set_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Patrols & Events Map", **(params.get("set_map_title") or {}))
        .call()
    )

    set_coverage_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_coverage_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Patrol Coverage Map", **(params.get("set_coverage_map_title") or {})
        )
        .call()
    )

    set_event_density_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_event_density_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            var="Event Density Map", **(params.get("set_event_density_title") or {})
        )
        .call()
    )

    set_traj_color_column = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_traj_color_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("set_traj_color_column") or {}))
        .call()
    )

    set_event_color_column = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_event_color_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("set_event_color_column") or {}))
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    density_weighting = (
        task(set_density_weighting)
        .validate()
        .set_task_instance_id("density_weighting")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("density_weighting") or {}))
        .call()
    )

    density_grid_options = (
        task(set_density_grid_options)
        .validate()
        .set_task_instance_id("density_grid_options")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(intersecting_only=False, **(params.get("density_grid_options") or {}))
        .call()
    )

    heatmap_opacity = (
        task(get_opacity_from_combined_params)
        .validate()
        .set_task_instance_id("heatmap_opacity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=density_grid_options,
            **(params.get("heatmap_opacity") or {}),
        )
        .call()
    )

    patrol_filters = (
        task(set_traj_filters)
        .validate()
        .set_task_instance_id("patrol_filters")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patrol_filters") or {}))
        .call()
    )

    bounding_box = (
        task(get_bounding_box)
        .validate()
        .set_task_instance_id("bounding_box")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("bounding_box") or {}))
        .call()
    )

    filter_point_coords = (
        task(get_filter_point_coords)
        .validate()
        .set_task_instance_id("filter_point_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("filter_point_coords") or {}))
        .call()
    )

    segment_filter = (
        task(get_segment_filter)
        .validate()
        .set_task_instance_id("segment_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("segment_filter") or {}))
        .call()
    )

    convert_patrols_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params.get("convert_patrols_tz") or {}),
        )
        .call()
    )

    filter_patrol_obs = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_patrols_tz,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            **(params.get("filter_patrol_obs") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_patrol_obs,
            trajectory_segment_filter=segment_filter,
            **(params.get("patrol_traj") or {}),
        )
        .call()
    )

    traj_rename_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_rename_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__patrol_subject": "patrol_subject",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_type__value": "patrol_type__value",
                "extra__patrol_status": "patrol_status",
            },
            raise_if_not_found=False,
            **(params.get("traj_rename_cols") or {}),
        )
        .call()
    )

    traj_with_date = (
        task(decompose_datetime)
        .validate()
        .set_task_instance_id("traj_with_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_cols,
            datetime_column="segment_start",
            components=["date"],
            remove_source=False,
            column_prefix=None,
            **(params.get("traj_with_date") or {}),
        )
        .call()
    )

    traj_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_with_date,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    traj_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("traj_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_temporal_index,
            input_column_name=set_traj_color_column,
            colormap=[
                "#FF9600",
                "#F23B0E",
                "#A100CB",
                "#F04564",
                "#03421A",
                "#3089FF",
                "#E26FFF",
                "#8C1700",
                "#002960",
                "#FFD000",
                "#B62879",
                "#680078",
                "#005A56",
                "#0056C7",
                "#331878",
                "#E76826",
            ],
            output_column_name="patrol_traj_colormap",
            **(params.get("traj_colormap") or {}),
        )
        .call()
    )

    convert_events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=event_type_display_names,
            timezone=get_timezone,
            columns=["time"],
            **(params.get("convert_events_tz") or {}),
        )
        .call()
    )

    events_filter = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("events_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_tz,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            **(params.get("events_filter") or {}),
        )
        .call()
    )

    pe_rename_grouper_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("pe_rename_grouper_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_filter,
            drop_columns=[],
            retain_columns=[],
            rename_columns={"patrol_type": "patrol_type__value"},
            raise_if_not_found=False,
            **(params.get("pe_rename_grouper_cols") or {}),
        )
        .call()
    )

    pe_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("pe_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pe_rename_grouper_cols,
            time_col="patrol_start_time",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("pe_add_temporal_index") or {}),
        )
        .call()
    )

    events_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("events_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pe_add_temporal_index,
            input_column_name=set_event_color_column,
            colormap="tab20b",
            output_column_name="event_type_colormap",
            **(params.get("events_colormap") or {}),
        )
        .call()
    )

    traj_cols_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("traj_cols_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_colormap,
            columns=["patrol_serial_number", "patrol_type__value"],
            **(params.get("traj_cols_to_string") or {}),
        )
        .call()
    )

    pe_cols_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("pe_cols_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_colormap,
            columns=["patrol_serial_number", "patrol_type__value"],
            **(params.get("pe_cols_to_string") or {}),
        )
        .call()
    )

    split_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_cols_to_string,
            groupers=groupers,
            **(params.get("split_traj_groups") or {}),
        )
        .call()
    )

    split_event_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_event_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=pe_cols_to_string,
            groupers=groupers,
            **(params.get("split_event_groups") or {}),
        )
        .call()
    )

    summary_groupby = (
        task(set_list_of_string_vars)
        .validate()
        .set_task_instance_id("summary_groupby")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("summary_groupby") or {}))
        .call()
    )

    summary_metrics = (
        task(set_patrol_summary_metrics)
        .validate()
        .set_task_instance_id("summary_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("summary_metrics") or {}))
        .call()
    )

    summary_table_df = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("summary_table_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            reset_index=True,
            groupby_cols=summary_groupby,
            summary_params=summary_metrics,
            **(params.get("summary_table_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_traj_groups)
    )

    summary_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("summary_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "patrol_subject": "Ranger",
                "patrol_type__value": "Patrol Type",
                "patrol_status": "Patrol Status",
            },
            raise_if_not_found=False,
            **(params.get("summary_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=summary_table_df)
    )

    summary_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=None,
            widget_id=set_summary_title,
            table_config={
                "enable_sorting": True,
                "enable_filtering": False,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("summary_table") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=summary_rename)
    )

    summary_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("summary_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="summary_table",
            **(params.get("summary_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=summary_table)
    )

    summary_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("summary_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_summary_title, **(params.get("summary_widget") or {}))
        .map(argnames=["view", "data"], argvalues=summary_html)
    )

    summary_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("summary_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=summary_widget, **(params.get("summary_widget_merged") or {}))
        .call()
    )

    traj_display_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_display_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"segment_start": "Start", "speed_kmhr": "Speed (kph)"},
            raise_if_not_found=False,
            **(params.get("traj_display_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_traj_groups)
    )

    traj_polyline_layer = (
        task(create_polyline_layer)
        .validate()
        .set_task_instance_id("traj_polyline_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "color_column": "patrol_traj_colormap",
                "get_width": 3,
                "width_units": "pixels",
                "cap_rounded": True,
                "opacity": 1,
            },
            legend={
                "label_column": set_traj_color_column,
                "color_column": "patrol_traj_colormap",
            },
            tooltip_columns=["patrol_subject", "Start", "Speed (kph)"],
            **(params.get("traj_polyline_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=traj_display_rename)
    )

    events_display_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("events_display_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"time": "Event Time"},
            raise_if_not_found=False,
            **(params.get("events_display_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_event_groups)
    )

    event_point_layer = (
        task(create_point_layer)
        .validate()
        .set_task_instance_id("event_point_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"fill_color_column": "event_type_colormap", "get_radius": 5},
            legend={
                "label_column": set_event_color_column,
                "color_column": "event_type_colormap",
            },
            tooltip_columns=["Event Time", "event_type"],
            **(params.get("event_point_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=events_display_rename)
    )

    map_layers_zip = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("map_layers_zip")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                all_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[traj_polyline_layer, event_point_layer],
            **(params.get("map_layers_zip") or {}),
        )
        .call()
    )

    map_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("map_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Tracks / Events",
                "format_title": True,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_map_title,
            **(params.get("map_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=map_layers_zip)
    )

    map_ecomap_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("map_ecomap_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="ranger_map",
            **(params.get("map_ecomap_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=map_ecomap)
    )

    map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_map_title, **(params.get("map_widget") or {}))
        .map(argnames=["view", "data"], argvalues=map_ecomap_html)
    )

    map_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("map_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=map_widget, **(params.get("map_widget_merged") or {}))
        .call()
    )

    coverage_meshgrid = (
        task(call_meshgrid_from_combined_params)
        .validate()
        .set_task_instance_id("coverage_meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=traj_with_date,
            combined_params=density_grid_options,
            **(params.get("coverage_meshgrid") or {}),
        )
        .call()
    )

    grouped_coverage_density = (
        task(calculate_feature_density)
        .validate()
        .set_task_instance_id("grouped_coverage_density")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            meshgrid=coverage_meshgrid,
            geometry_type="line",
            sum_column=density_weighting,
            **(params.get("grouped_coverage_density") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_traj_groups)
    )

    coverage_normalized = (
        task(normalize_density_units)
        .validate()
        .set_task_instance_id("coverage_normalized")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sum_column=density_weighting, **(params.get("coverage_normalized") or {})
        )
        .mapvalues(argnames=["df"], argvalues=grouped_coverage_density)
    )

    coverage_legend_title = (
        task(get_density_legend_title)
        .validate()
        .set_task_instance_id("coverage_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            sum_column=density_weighting,
            title_prefix="Patrol Effort",
            **(params.get("coverage_legend_title") or {}),
        )
        .call()
    )

    coverage_sorted = (
        task(sort_values)
        .validate()
        .set_task_instance_id("coverage_sorted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="density",
            ascending=True,
            na_position="last",
            **(params.get("coverage_sorted") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=coverage_normalized)
    )

    coverage_drop_nan = (
        task(drop_nan_values_by_column)
        .validate()
        .set_task_instance_id("coverage_drop_nan")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="density", **(params.get("coverage_drop_nan") or {}))
        .mapvalues(argnames=["df"], argvalues=coverage_sorted)
    )

    coverage_classify = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("coverage_classify")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density",
            output_column_name="density_bins",
            classification_options={"scheme": "equal_interval", "k": 10},
            label_options={"label_ranges": True, "label_decimals": 1},
            **(params.get("coverage_classify") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=coverage_drop_nan)
    )

    coverage_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("coverage_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap="viridis",
            output_column_name="density_colormap",
            **(params.get("coverage_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=coverage_classify)
    )

    coverage_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("coverage_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"density": "Patrol Effort"},
            raise_if_not_found=True,
            **(params.get("coverage_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=coverage_colormap)
    )

    coverage_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("coverage_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "density_colormap",
                "get_line_width": 0,
                "opacity": heatmap_opacity,
            },
            legend={"label_column": "density_bins", "color_column": "density_colormap"},
            tooltip_columns=["Patrol Effort"],
            **(params.get("coverage_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=coverage_rename)
    )

    coverage_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("coverage_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": coverage_legend_title,
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_coverage_map_title,
            **(params.get("coverage_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=coverage_layer)
    )

    coverage_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("coverage_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="coverage_map",
            **(params.get("coverage_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=coverage_ecomap)
    )

    coverage_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("coverage_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_coverage_map_title, **(params.get("coverage_widget") or {}))
        .map(argnames=["view", "data"], argvalues=coverage_html)
    )

    coverage_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("coverage_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=coverage_widget, **(params.get("coverage_widget_merged") or {})
        )
        .call()
    )

    event_meshgrid = (
        task(call_meshgrid_from_combined_params)
        .validate()
        .set_task_instance_id("event_meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=events_colormap,
            combined_params=density_grid_options,
            **(params.get("event_meshgrid") or {}),
        )
        .call()
    )

    grouped_event_density = (
        task(calculate_feature_density)
        .validate()
        .set_task_instance_id("grouped_event_density")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            meshgrid=event_meshgrid,
            geometry_type="point",
            sum_column=None,
            **(params.get("grouped_event_density") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_event_groups)
    )

    ed_sorted = (
        task(sort_values)
        .validate()
        .set_task_instance_id("ed_sorted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="density",
            ascending=True,
            na_position="last",
            **(params.get("ed_sorted") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=grouped_event_density)
    )

    ed_drop_nan = (
        task(drop_nan_values_by_column)
        .validate()
        .set_task_instance_id("ed_drop_nan")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="density", **(params.get("ed_drop_nan") or {}))
        .mapvalues(argnames=["df"], argvalues=ed_sorted)
    )

    ed_classify = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("ed_classify")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density",
            output_column_name="density_bins",
            classification_options={"scheme": "equal_interval", "k": 10},
            label_options={"label_ranges": True, "label_decimals": 0},
            **(params.get("ed_classify") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ed_drop_nan)
    )

    ed_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("ed_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap="RdYlGn_r",
            output_column_name="density_colormap",
            **(params.get("ed_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ed_classify)
    )

    ed_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("ed_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"density": "Event Count"},
            raise_if_not_found=True,
            **(params.get("ed_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=ed_colormap)
    )

    ed_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("ed_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "density_colormap",
                "get_line_width": 0,
                "opacity": heatmap_opacity,
            },
            legend={"label_column": "density_bins", "color_column": "density_colormap"},
            tooltip_columns=["Event Count"],
            **(params.get("ed_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=ed_rename)
    )

    ed_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("ed_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": "Number of Events",
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_event_density_title,
            **(params.get("ed_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=ed_layer)
    )

    ed_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("ed_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="event_density_map",
            **(params.get("ed_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=ed_ecomap)
    )

    ed_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("ed_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_event_density_title, **(params.get("ed_widget") or {}))
        .map(argnames=["view", "data"], argvalues=ed_html)
    )

    ed_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("ed_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=ed_widget, **(params.get("ed_widget_merged") or {}))
        .call()
    )

    ranger_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("ranger_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                summary_widget_merged,
                map_widget_merged,
                coverage_widget_merged,
                ed_widget_merged,
            ],
            groupers=groupers,
            time_range=time_range,
            **(params.get("ranger_dashboard") or {}),
        )
        .call()
    )

    return ranger_dashboard
