# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    set_patrol_summary_metrics as set_patrol_summary_metrics,
)
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import (
    set_list_of_string_vars as set_list_of_string_vars,
)
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import (
    get_patrol_observations_from_patrols_df_and_combined_params as get_patrol_observations_from_patrols_df_and_combined_params,
)
from ecoscope.platform.tasks.io import (
    get_patrols_from_combined_params as get_patrols_from_combined_params,
)
from ecoscope.platform.tasks.io import (
    get_spatial_features_group as get_spatial_features_group,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import (
    set_patrols_and_patrol_events_params as set_patrols_and_patrol_events_params,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_table_widget_single_view as create_table_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_table as draw_table
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_spatial_index as add_spatial_index,
)
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    convert_column_values_to_string as convert_column_values_to_string,
)
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    extract_spatial_grouper_feature_group_names as extract_spatial_grouper_feature_group_names,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    resolve_spatial_feature_groups_for_spatial_groupers as resolve_spatial_feature_groups_for_spatial_groupers,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_bounding_box as get_bounding_box,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_filter_point_coords as get_filter_point_coords,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    get_segment_filter as get_segment_filter,
)
from ecoscope_workflows_ext_custom.tasks.config import (
    set_traj_filters as set_traj_filters,
)
from ecoscope_workflows_ext_custom.tasks.transformation import (
    decompose_datetime as decompose_datetime,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    er_patrol_params = (
        task(set_patrols_and_patrol_events_params)
        .validate()
        .set_task_instance_id("er_patrol_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_types=[],
            include_patrol_details=True,
            raise_on_empty=False,
            truncate_to_time_range=True,
            include_null_geometry=True,
            sub_page_size=100,
            **(params.get("er_patrol_params") or {}),
        )
        .call()
    )

    prefetch_patrols = (
        task(get_patrols_from_combined_params)
        .validate()
        .set_task_instance_id("prefetch_patrols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=er_patrol_params, **(params.get("prefetch_patrols") or {})
        )
        .call()
    )

    patrol_obs = (
        task(get_patrol_observations_from_patrols_df_and_combined_params)
        .validate()
        .set_task_instance_id("patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            patrols_df=prefetch_patrols,
            combined_params=er_patrol_params,
            **(params.get("patrol_obs") or {}),
        )
        .call()
    )

    patrol_filters = (
        task(set_traj_filters)
        .validate()
        .set_task_instance_id("patrol_filters")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("patrol_filters") or {}))
        .call()
    )

    bounding_box = (
        task(get_bounding_box)
        .validate()
        .set_task_instance_id("bounding_box")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("bounding_box") or {}))
        .call()
    )

    filter_point_coords = (
        task(get_filter_point_coords)
        .validate()
        .set_task_instance_id("filter_point_coords")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("filter_point_coords") or {}))
        .call()
    )

    segment_filter = (
        task(get_segment_filter)
        .validate()
        .set_task_instance_id("segment_filter")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(filters=patrol_filters, **(params.get("segment_filter") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    spatial_group_ids = (
        task(extract_spatial_grouper_feature_group_names)
        .validate()
        .set_task_instance_id("spatial_group_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=groupers, **(params.get("spatial_group_ids") or {}))
        .call()
    )

    fetch_all_spatial_feature_groups = (
        task(get_spatial_features_group)
        .validate()
        .set_task_instance_id("fetch_all_spatial_feature_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            **(params.get("fetch_all_spatial_feature_groups") or {}),
        )
        .map(argnames=["spatial_features_group_name"], argvalues=spatial_group_ids)
    )

    resolved_groupers = (
        task(resolve_spatial_feature_groups_for_spatial_groupers)
        .validate()
        .set_task_instance_id("resolved_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=groupers,
            spatial_feature_groups=fetch_all_spatial_feature_groups,
            **(params.get("resolved_groupers") or {}),
        )
        .call()
    )

    set_summary_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_summary_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Patrol Effort Summary", **(params.get("set_summary_title") or {}))
        .call()
    )

    convert_patrols_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_patrols_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_obs,
            timezone=get_timezone,
            columns=["patrol_start_time", "patrol_end_time", "fixtime"],
            **(params.get("convert_patrols_tz") or {}),
        )
        .call()
    )

    filter_patrol_obs = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_patrol_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_patrols_tz,
            bounding_box=bounding_box,
            filter_point_coords=filter_point_coords,
            roi_gdf=None,
            roi_name=None,
            reset_index=False,
            **(params.get("filter_patrol_obs") or {}),
        )
        .call()
    )

    patrol_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("patrol_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=filter_patrol_obs,
            trajectory_segment_filter=segment_filter,
            **(params.get("patrol_traj") or {}),
        )
        .call()
    )

    traj_rename_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("traj_rename_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=patrol_traj,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__patrol_subject": "patrol_subject",
                "extra__patrol_id": "patrol_id",
                "extra__patrol_serial_number": "patrol_serial_number",
                "extra__patrol_type__value": "patrol_type__value",
                "extra__patrol_status": "patrol_status",
            },
            raise_if_not_found=False,
            **(params.get("traj_rename_cols") or {}),
        )
        .call()
    )

    traj_with_date = (
        task(decompose_datetime)
        .validate()
        .set_task_instance_id("traj_with_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_rename_cols,
            datetime_column="segment_start",
            components=["date"],
            remove_source=False,
            column_prefix=None,
            **(params.get("traj_with_date") or {}),
        )
        .call()
    )

    traj_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_with_date,
            time_col="segment_start",
            groupers=resolved_groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    traj_add_spatial_index = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("traj_add_spatial_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=traj_add_temporal_index,
            groupers=resolved_groupers,
            **(params.get("traj_add_spatial_index") or {}),
        )
        .call()
    )

    traj_cols_to_string = (
        task(convert_column_values_to_string)
        .validate()
        .set_task_instance_id("traj_cols_to_string")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_spatial_index,
            columns=["patrol_serial_number", "patrol_type__value"],
            **(params.get("traj_cols_to_string") or {}),
        )
        .call()
    )

    split_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_cols_to_string,
            groupers=resolved_groupers,
            **(params.get("split_traj_groups") or {}),
        )
        .call()
    )

    summary_groupby = (
        task(set_list_of_string_vars)
        .validate()
        .set_task_instance_id("summary_groupby")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("summary_groupby") or {}))
        .call()
    )

    summary_metrics = (
        task(set_patrol_summary_metrics)
        .validate()
        .set_task_instance_id("summary_metrics")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("summary_metrics") or {}))
        .call()
    )

    summary_table_df = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("summary_table_df")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            reset_index=True,
            groupby_cols=summary_groupby,
            summary_params=summary_metrics,
            **(params.get("summary_table_df") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_traj_groups)
    )

    summary_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("summary_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "patrol_subject": "Patrol Subject",
                "patrol_type__value": "Patrol Type",
                "patrol_status": "Patrol Status",
            },
            raise_if_not_found=False,
            **(params.get("summary_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=summary_table_df)
    )

    summary_table = (
        task(draw_table)
        .validate()
        .set_task_instance_id("summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            columns=None,
            widget_id=set_summary_title,
            table_config={
                "enable_sorting": True,
                "enable_filtering": False,
                "enable_download": True,
                "hide_header": False,
            },
            **(params.get("summary_table") or {}),
        )
        .mapvalues(argnames=["dataframe"], argvalues=summary_rename)
    )

    summary_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("summary_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="summary_table",
            **(params.get("summary_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=summary_table)
    )

    summary_widget = (
        task(create_table_widget_single_view)
        .validate()
        .set_task_instance_id("summary_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_summary_title, **(params.get("summary_widget") or {}))
        .map(argnames=["view", "data"], argvalues=summary_html)
    )

    summary_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("summary_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=summary_widget, **(params.get("summary_widget_merged") or {}))
        .call()
    )

    patrol_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("patrol_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[summary_widget_merged],
            groupers=resolved_groupers,
            time_range=time_range,
            **(params.get("patrol_dashboard") or {}),
        )
        .call()
    )

    return patrol_dashboard
